language: swift
os: osx
osx_image: xcode9.0
before_install:
script:
  - xcodebuild clean -scheme PDFImage | xcpretty
  - xcodebuild -project PDFImage.xcodeproj -scheme PDFImage -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' | xcpretty
  
